### ISSUE TITLE
No binary for Windows

### ISSUE THREAD

**Issue by tyeeman** [waynezhang/foto#1]
I would like to try foto. Can you make a Windows binary?

**Comment by tyeeman** [comment]
I made a binary for windows and it started serving on port 5000, but when I try to access it in my browser I get this error - 

```
ERROR: Failed to get photos from ~/photos/section-1 (CreateFile ~/photos/section-1: The system canno
t find the path specified.)
ERROR: Failed to get photos from ~/photos/section-2 (CreateFile ~/photos/section-2: The system canno
t find the path specified.)
2022/10/17 19:39:32 http: panic serving 127.0.0.1:50914: open templates\template.html: The system ca
nnot find the path specified.
```

Should it work on Windows? I don't have /photos/section-1 anywhere. I put a few photos in the media folder.

**Comment by tyeeman** [comment]
OK, I got it working!! I had to put foto.exe into my_site folder to make it work. Is this how it should work?

**Comment by tyeeman** [comment]
I see 5 cdn requests. If any of those die I guess the gallery won't work anymore?

**Comment by waynezhang** [comment]
@tyeeman sorry I didn't notice this. Good to hear that you've made it working. I pushed [a new commit](https://github.com/waynezhang/foto/commit/24443677fbb4fd8f70c667fe5cb708ef95df3e75) to support changing image order.

**Comment by tyeeman** [comment]
Sorry for the delay. I just tried the new version with ascending=true but the result is still descending. Please try at your end.

**Comment by waynezhang** [comment]
@tyeeman sorry it's been a long time. Could you please check the version of `foto` that you are using?
