### ISSUE TITLE
Scrolling down before images are loaded causes muddled layout (iOS Safari)

### ISSUE THREAD

**Issue by fkxr-dev** [waynezhang/foto#35]
Hi,

Sorry for the sudden train of issues, this one's relatively minor but I thought I'd point it out:

It's possible to get quite a messed up layout of the photo grids if you manage to outpace the image fetching by scrolling down the page rapidly, shortly after it loads. The section of the page that doesn't have images displayed yet by the time you scroll down to it, will get a bit of a garbled layout, as if the flow grid isn't re-evaluated after the images' dimensions are actually known. Whatever was already loaded before scrolling off-screen seems to stay in a correct layout.

I've at least confirmed this to be somewhat consistent on iOS Safari, have not been able to reproduce this on other browsers as of yet (but they also tend to load a bit faster so maybe on bad connections this would reproduce on others). This will persist until you force refresh the page (plus it's then also harder to reproduce as everything is hot in the cache, too).

<img width="459" alt="image" src="https://github.com/user-attachments/assets/734ccc0a-5585-4902-8e8b-e8e70c9b8bd0">

It's probably easiest to show with a video:

https://github.com/user-attachments/assets/4bd5216a-c676-4a82-8b9d-7ef6616a8ff0

Frontend is sadly quite outside my ballpark so I'm unable to suggest a patch for this at this point.

Thanks!

**Comment by waynezhang** [comment]
@fkxr-dev hi, thanks for reporting this. This seems very similar to #8. It requires some fix on template file which is extracted on very beginning and won't be updated. Could you please take a look at it?

**Comment by fkxr-dev** [comment]
Hey, thanks once more for the project and the quick replies! This does seem to indeed have been the same underlying issue, modifying the template as per the change linked in #8 has resolved the issue.

Thanks!
