### ISSUE TITLE
Allow greater customization of lightbox elements

### ISSUE THREAD

**Issue by kowalabearhugs** [waynezhang/foto#38]
Is it possible to add toggles to the toml file to control the inclusion or visibility of the elements of the lightbox? Specifically the right-left control arrows, magnifying glass icon, and image count.

The functionality would remain the same, but the visible presence of these elements would be optional.

**Comment by waynezhang** [comment]
@kowalabearhugs yes. `foto` is passing everything defined in `foto.toml` to the template. So technically you can do this without binary update. This will require some modification on both the toml file and template html file, like [this](https://github.com/waynezhang/foto/commit/de1e6e4ad1414621e1a404104a39ee78b1a0ddb4).
However this seems an interesting feature so I just included it in the newest release today. You still need to re-create the whole directory or copy the new template file to it though.

**Comment by kowalabearhugs** [comment]
Wonderful. Your prompt response and enhancements are much appreciated.

I just ran some tests using Firefox and Safari. When configured in this instance no arrows appear: show_arrow_prev = false, show_arrow_next = true

If prev is _true_ and next _false_ then it correctly only shows the prev arrow.

All other configurations appear to work correctly. This really doesn't affect my use-case as I intend to always pass the same value to both arrows. IMO consolidating the arrows into a single toggle option would be a a suitable offering.

**Comment by waynezhang** [comment]
@kowalabearhugs thanks for the testing! I also found this and thought it should be a bug on PhotoSwipe. But consolidating the arrows is a great idea. I'll push a fix later.

**Comment by waynezhang** [comment]
@kowalabearhugs fixed [here](https://github.com/waynezhang/foto/commit/003a432ff22aab0af6c8c41c57edc41870f215e9) and pushed 1.5.1.

**Comment by kowalabearhugs** [comment]
I tested a 1.5.1 site build on FF and Safari and the lightbox toggles work in all configurations. Thank you!

**Comment by waynezhang** [comment]
Thanks for testing!
