### ISSUE TITLE
Duplicate slug names cause sections to fail grid layout

### ISSUE THREAD

**Issue by fkxr-dev** [waynezhang/foto#4]
Here's a weird one, obviously a user error here but I ran into a problem where one of my sections would refuse to appear in a grid layout. All the images would appear full-width in a one-wide list, if that makes sense. I tracked it down to the problem being a duplicated slug identifier for two sections in my TOML, renaming one of them caused the issue to go away.

Naturally slugs ought to be unique and this is technically a user error, maybe some error reporting during building would be enough to address this already, but I figured it's worth reporting here nonetheless.

So the reproduction steps as far as I can tell are:

- Make two sections
- Set their slug names to identical text
- Add `layout.minColumn` or more images to each section
- The first section defined in the TOML file should appear correctly, the second one will not have a grid layout at all and simply show up as a list of images.

Let me know if you'd need any further information!

**Comment by waynezhang** [comment]
@fkxr-dev thanks for reporting! I just push a new version `v.1.08` to add a guard logic. Could you please take a look at it? I did a big refactoring and hope it didn't break anything. 😆

**Comment by fkxr-dev** [comment]
I can have a look later this week and will let you know. One related thing I noticed in the interim of testing this (on 1.0.7) was that when magnified/opened in the full-screen viewer, the exif-rotated portrait shots come out as squashed to their ‘original’ unrotated aspect ratio, the thumbnails are fine.

Thanks for the quick fixes!

**Comment by waynezhang** [comment]
@fkxr-dev thanks!

> One related thing I noticed in the interim of testing this (on 1.0.7) was that when magnified/opened in the full-screen viewer, the exif-rotated portrait shots come out as squashed to their ‘original’ unrotated aspect ratio, the thumbnails are fine.

I see. Let me check it when I got time later. BTW did you try to clear both the cache (.foto folder) of foto and the cache of browser?

**Comment by fkxr-dev** [comment]
On the latest code (pulled from main) I'm now getting (correctly): 

`ERROR: Failed to build index. (Slug "20231229" already exists. Slug needs to be unique.)` -- so the guards against duplicate slugs seems to work.

The squashed images in the enlarged view also seem to be resolved now; tried on a few different browsers and they all seem happy.

**Comment by waynezhang** [comment]
@fkxr-dev Nice! Thanks for checking!
