### ISSUE TITLE
lazy loading / lozad

### ISSUE THREAD

**Issue by vredesbyyrd** [waynezhang/foto#8]
First I want to say - awesome project! Very simple and I appreciate the ability to customize. 

Is `lozad` working properly for you? I have only tested on my localhost but all images are loaded almost immediately, and in a glitchy manner. It appears like images are fighting for placement as they load. I see the same/similar behavior on firefox, chrome and webkit based browsers, all running in linux. 

I should state I have about zero web development experience. If you have any tips on debugging - or anyway I can get you some useful logs please let me know. 

Thanks for your time!

**Comment by waynezhang** [comment]
@vredesbyyrd thanks for the feedback! `lozad` seems be working fine but there was something wrong in grid computing logic. I tried to add preset sizes to the grid and it should work fine right now. Could you please take a look at it with v1.2.1? If you are using the template you need to fix the template like [this](https://github.com/waynezhang/foto/commit/35197f60525c52c6f26f5ea460f3ea957e3e6073).

**Comment by vredesbyyrd** [comment]
Hey, I appreciate the quick fix. I just tested the changes and everything is loading as expected now, eg, images only load once there within the view and they load "cleanly"...looks great :) 

Thanks again for sharing this awesome project!
